name: Build and Release

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          g++ -o YT-Compression.exe src/YTCompression.cpp

      - name: Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MY_APP_VERSION: ${{ secrets.VER }}
        with:
          tag_name: ${{ secrets.VER }}
          release_name: Release ${{ secrets.VER }}
          body: Automated Release
          draft: false
          prerelease: false
