name: Build and Release

on:
  push:
    tags:
      - '*'  # Trigger on all tags

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          g++ -o YT-Compression.exe src/YTCompression.cpp

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: Automated Release
          artifacts: './YT-Compression.exe'
          artifactContentType: 'application/octet-stream'
          token: ${{ secrets.GITHUB_TOKEN }}
